### PR TITLE
Made it impossible to ping everyone or here through the bot

### PR DESCRIPTION
**Pull request by lucasfortheday**
Added a simple @everyone and @here "protection". Have not tested it yet, but it should work in theory.

### CODE REVIEW

**Comment by nishi7409** [comment]
Not a bad fix, but I plan on pushing a fix along with other updates in the future.  I'll keep this opened tho for rn tho 👍

**Comment by nishi7409** [comment]
image

**Comment by lucasfortheday** [comment]
yeah, I'm poet.

**Comment by nishi7409** [comment]
https://github.com/nishi7409/Auxiliary/commit/f54d77fcf9956b3209343f17df385e71b23d84b2

**Pull request closed without merging**
